<?php /** @var \BeeGame\Templating\PHtmlTemplateEngine $this */ ?>
<?php /** @var array $params */ ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>The Bee Game</title>
    </head>
    <body>

        <h1>Enter your name below to start a new game</h1>
        <form method="post" action="/new-game">
            <label for="playerName">Name:</label>
            <input required="required" id="playerName" type="text" name="playerName">
            <input type="submit" name="submit" value="Start new game">
        </form>
    </body>
</html>